site_name: EthicalHacking
repo_url: https://github.com/techtimefly/ethicalhacking
theme:
  name: material
  palette: 
    primary: black
    scheme: slate
    
  features:
    #- toc.follow
    - toc.integrate
    - navigation.top

plugins: 
 - blog
 - tags
 - search

markdown_extensions:
  - admonition