site_name: EthicalHacking
repo_url: https://github.com/techtimefly/ethicalhacking
edit_uri: edit/main/docs/
theme:
  name: material
  palette: 
    primary: black
    scheme: slate
    
  features:
    - content.action.view
    - content.action.edit
    - toc.integrate
    - navigation.top

plugins: 
 - blog
 - tags
 - search
 - git-committers:
      repository: techtimefly/ethicalhacking
      branch: main

markdown_extensions:
  - admonition