site_name: EthicalHacking
repo_url: https://github.com/techtimefly/ethicalhacking
edit_uri: edit/main/docs/
theme:
  name: material
  palette: 
    primary: black
    scheme: slate
    
  features:
    - content.action.edit
    - content.action.view
    - navigation.expand
    - navigation.indexes 
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

plugins: 
 - blog:

 - tags
 - search

markdown_extensions:
  - admonition
